version: 0.2
            
phases:

  install: 
    commands:
      - go version

  pre_build: 
    commands:

      # Run all tests included with our application
      #- go test

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - 'app'
    - 'appspec.yml'
    - 'buildspec.yml'
    - 'BeforeInstall.sh'
    - 'AfterInstall.sh'
    - 'ValidateService.sh'  
    - 'ApplicationStop.sh'
    - 'ApplicationStart.sh'